package tools

import (
	"context"
	"fmt"
	"strings"

	sdk "github.com/modelcontextprotocol/go-sdk/mcp"
)

type harnessInstallInput struct {
	// Language can override the project's primary_language for this PINDOC.md
	// render. Optional; falls back to the project setting.
	Language string `json:"language,omitempty" jsonschema:"en|ko|auto; default = project primary_language"`
}

type harnessInstallOutput struct {
	// SuggestedPath is relative to the repo root. The agent writes Body
	// here using its own filesystem tool (Pindoc MCP does not touch the
	// filesystem — separation of concerns).
	SuggestedPath string `json:"suggested_path"`

	// Body is the full PINDOC.md content the agent should write.
	Body string `json:"body"`

	// ClaudeMdIncludeLine is a one-line directive the agent appends to
	// CLAUDE.md (or AGENTS.md) so every future session auto-loads PINDOC.md.
	ClaudeMdIncludeLine string `json:"claude_md_include_line"`

	// Message gives the agent a plain-English summary of what to do next.
	Message string `json:"message"`

	// Metadata the template was rendered from, so the agent can explain
	// choices to the user.
	RenderedFor RenderedFor `json:"rendered_for"`
}

type RenderedFor struct {
	ProjectSlug     string `json:"project_slug"`
	PrimaryLanguage string `json:"primary_language"`
	Version         string `json:"pindoc_server_version"`
}

// RegisterHarnessInstall wires pindoc.harness.install. Generates a
// PINDOC.md body tuned to the active project and returns it for the agent
// to persist. Pindoc is write-only via agents even for its own harness —
// the server never writes filesystem; the agent does.
func RegisterHarnessInstall(server *sdk.Server, deps Deps) {
	sdk.AddTool(server,
		&sdk.Tool{
			Name:        "pindoc.harness.install",
			Description: "Return the PINDOC.md body this project should adopt and the one-line CLAUDE.md include that loads it. Write the returned body to PINDOC.md at the repo root, and append the include line to CLAUDE.md (or AGENTS.md). Re-run to regenerate after upgrading the server — the spec evolves with the server version.",
		},
		func(ctx context.Context, _ *sdk.CallToolRequest, in harnessInstallInput) (*sdk.CallToolResult, harnessInstallOutput, error) {
			var projName, projLang string
			err := deps.DB.QueryRow(ctx, `
				SELECT name, primary_language FROM projects WHERE slug = $1
			`, deps.ProjectSlug).Scan(&projName, &projLang)
			if err != nil {
				return nil, harnessInstallOutput{}, fmt.Errorf("project lookup: %w", err)
			}

			lang := strings.ToLower(strings.TrimSpace(in.Language))
			if lang == "" || lang == "auto" {
				lang = projLang
			}

			body := renderPindocMD(projName, deps.ProjectSlug, lang, deps.Version)

			return nil, harnessInstallOutput{
				SuggestedPath:       "PINDOC.md",
				Body:                body,
				ClaudeMdIncludeLine: "@PINDOC.md",
				Message: strings.TrimSpace(fmt.Sprintf(`
Write the returned body to PINDOC.md at the repo root. Then append this
exact line to the end of CLAUDE.md (or AGENTS.md if you use that):
    @PINDOC.md
Future Claude Code sessions will auto-load PINDOC.md and follow the
Pindoc Harness rules (Pre-flight Check before writes, Referenced
Confirmation when asking the user for approval, agent-only write
surface).
`)),
				RenderedFor: RenderedFor{
					ProjectSlug:     deps.ProjectSlug,
					PrimaryLanguage: lang,
					Version:         deps.Version,
				},
			}, nil
		},
	)
}

// renderPindocMD is intentionally one string template for M1. When PINDOC.md
// stabilises (see docs/09-pindoc-md-spec.md) we split this out to a
// dedicated package with per-section conditionals. Today it is under 100
// lines — a single string is simpler to review.
func renderPindocMD(projectName, projectSlug, language, serverVersion string) string {
	return fmt.Sprintf(`# PINDOC.md — Harness for %s

<!-- Generated by pindoc.harness.install · server %s · language %s -->
<!-- Do not hand-edit. Re-run pindoc.harness.install to regenerate. -->

This file is the Pindoc Harness. Claude Code (and Cursor / Codex / Cline)
load it on every session start and follow the rules below.

## Project

- slug: %s
- primary_language: %s

## Write surface

- Pindoc artifacts (pindoc.artifact.propose) are the only way new long-lived
  documents enter this repo. The agent writes. The human approves or
  redirects. The human does not type into a wiki.
- Artifact types available: Decision, Analysis, Debug, Flow, Task, TC,
  Glossary (Tier A core) + Feature, APIEndpoint, Screen, DataModel (Tier B
  Web-SaaS pack active on this project).

## Pre-flight Check protocol (M0.5)

Before calling pindoc.artifact.propose:

1. Call pindoc.project.current once per session to pin scope.
2. Call pindoc.area.list and pick an existing area_slug; use 'misc' if
   nothing fits. Never invent an area_slug.
3. Assemble title (concise, unique), body_markdown, type, area_slug,
   author_id (your agent ID).
4. If propose returns Status=not_ready, read the checklist and the
   suggested_actions, fix every ✗ item, then retry. Do not surface the
   raw error to the user without attempting the suggested_actions first.

## Referenced Confirmation protocol (M0.6)

When you ask the user for approval, review, or a decision, always include:

- A one-line summary of what you are proposing.
- A clickable URL to the relevant artifact(s), commit range, or external
  doc. Never a bare "should I proceed?" without a link the user can read.
- If multiple candidates: list each with its own link. 3+ candidates
  should be packaged as one artifact and linked once.

This protocol is how Pindoc helps the human stay in command without
reading every token you produced. Follow it.

## Artifact hygiene

- Body language: %s.
- Title: concise and unique. The exact-title conflict check will reject
  duplicates. If your proposal matches an existing artifact, call
  pindoc.artifact.read on the existing one and either supersede it or
  pick a more specific title.
- Long bodies: prefer H2/H3 section structure. The embedding layer
  chunks on heading boundaries, so well-structured markdown becomes
  better search results for free.
- Code references: use relative paths or full GitHub blob URLs with
  line ranges. The agent at the other end of the graph can follow these.

## When in doubt

- pindoc.project.current → you lost track of the project ID.
- pindoc.area.list       → you are unsure which scope a new artifact belongs to.
- pindoc.artifact.read   → a user pasted a Pindoc URL or referred to
                           an existing artifact by name.
- pindoc.artifact.search → (Phase 3+) semantic retrieval before writing
                           anything new, so you don't duplicate.

## Do not

- Do not create artifacts whose body is just a summary of the user's last
  message. Wait for a genuine checkpoint (completed debugging, a
  decision reached, a feature landed, a lesson learned).
- Do not invent new artifact types. Stick to the whitelist above.
- Do not edit PINDOC.md itself by hand. Re-run pindoc.harness.install
  after upgrading the server.
`,
		projectName, serverVersion, language,
		projectSlug, language,
		languageLabel(language),
	)
}

func languageLabel(code string) string {
	switch code {
	case "ko":
		return "Korean (한국어) as the primary voice; English identifiers and MCP tool names stay English"
	case "en":
		return "English"
	default:
		return code
	}
}
