package tools

import (
	"strings"
	"testing"
)

func TestSlugBrevityAdvisoryAutoGeneratedLongSlug(t *testing.T) {
	in := artifactProposeInput{
		Type:  "Task",
		Title: "Reader TOC를 Sidecar로 이전하고 4단 구조를 정리",
	}
	warnings, actions := slugBrevityAdvisory(in, slugify(in.Title))
	if len(warnings) != 1 || warnings[0] != "SLUG_VERBOSE" {
		t.Fatalf("warnings = %v, want [SLUG_VERBOSE]", warnings)
	}
	if len(actions) < 2 {
		t.Fatalf("actions = %v, want current-slug note plus candidate", actions)
	}
	if !strings.Contains(strings.Join(actions, "\n"), "task-reader-toc를-sidecar로") {
		t.Fatalf("actions should include a title-derived Unicode-preserving candidate, got %v", actions)
	}
}

func TestSlugBrevityAdvisoryShortAutoSlug(t *testing.T) {
	in := artifactProposeInput{Type: "Task", Title: "짧은 제목"}
	warnings, actions := slugBrevityAdvisory(in, slugify(in.Title))
	if len(warnings) != 0 || len(actions) != 0 {
		t.Fatalf("short auto slug should not warn, warnings=%v actions=%v", warnings, actions)
	}
}

func TestSlugBrevityAdvisoryExplicitSlug(t *testing.T) {
	in := artifactProposeInput{
		Type:  "Task",
		Title: "Reader TOC를 Sidecar로 이전하고 4단 구조를 정리",
		Slug:  "intentionally-long-reader-toc-sidecar-migration",
	}
	warnings, actions := slugBrevityAdvisory(in, in.Slug)
	if len(warnings) != 0 || len(actions) != 0 {
		t.Fatalf("explicit slug should not warn, warnings=%v actions=%v", warnings, actions)
	}
}
